### ISSUE TITLE
Weird tooltips in Inventory Briefing

### ISSUE THREAD

**Issue by oxypomme** [GdC-Framework/GdC_lib#112]
Mauvaise interprétations de certains saut de lignes (dû à certains mods utilisant `<br/>` au lieu de `<br />`) :

[arma3_x64_2022-09-09_21-14-55.webm](https://user-images.githubusercontent.com/34627360/189428534-e6a1ba88-1ffd-4f32-aaf0-9fac3a9cb59f.webm)

Les apostrophes cassent la chaîne de caractères et empêchent l'affichage de la description :

![arma3_x64_2022-09-09_21-16-16](https://user-images.githubusercontent.com/34627360/189428537-25e4bdd1-e50c-4669-a4bc-b982b7209962.png)

**Comment by oxypomme** [comment]
**Proposition pour le problème des `<br />` :**

Dans `gdc_lib_main/functions/util/fn_getInventoryBriefing.sqf` :
Remplacer 
```sqf
_desc = [(getText(_cfg >> "descriptionShort")), "<br />", true] call BIS_fnc_splitString;
_desc = _desc joinString endl;
````
par
```sqf
_desc  = (getText(_cfg >> "descriptionShort")) regexReplace ["<br\s?\/?>/i", endl];
````

**Comment by oxypomme** [comment]
Fixé par (b8d81f0)[https://github.com/GdC-Framework/GdC_lib/commit/b8d81f063296488ca9a7732e78bf4e4271d7e982].

Cependant une description contenant des guillemets (possible mais je doute qu'il y en existe) peut encore engendrer des problèmes. Ajouter `_desc regexReplace ["""/g", "''"];` avant le format peut régler le problème (cf. [1e commentaire](https://github.com/GdC-Framework/GdC_lib/issues/112#issuecomment-1256803337)).

**Comment by Sparfell** [comment]
Trop bien ! J'avais remarqué le problème mais la flemme de trouver une solution. XD
Je ne connaissais pas regexreplace !!

**Comment by oxypomme** [comment]
> Trop bien ! J'avais remarqué le problème mais la flemme de trouver une solution. XD
> Je ne connaissais pas regexreplace !!

Moi non plus ! Merci @Migoyan :D

**Comment by Sparfell** [comment]
> Fixé par [b8d81f0](https://github.com/GdC-Framework/GdC_lib/commit/b8d81f063296488ca9a7732e78bf4e4271d7e982).
> 
> Cependant une description contenant des guillemets (possible mais je doute qu'il y en existe) peut encore engendrer des problèmes. Ajouter `_desc regexReplace ["""/g", "''"];` avant le `format` peut régler le problème (cf. [1e commentaire](https://github.com/GdC-Framework/GdC_lib/issues/112#issuecomment-1256803337)).

Fixé dans [5142f9e](https://github.com/GdC-Framework/GdC_lib/commit/5142f9ea83880293fa653a93f47f3bb78f1f8f1d)
