### ISSUE TITLE
Parachutage d'ia sur demande

### ISSUE THREAD

**Issue by TheShinriel** [GdC-Framework/GdC_lib#14]
Créer un script parachutant un nombre d'ia à une position donnée

**Comment by Sweedn** [comment]
Pas moyen d'effectuer ça via gdc_halo, sinon le paradrop RHS ne marche pas ?

**Comment by Sparfell** [comment]
Non gdc_halo n'est pas fait pour ça.

**Comment by Mysteryjuju** [comment]
Développement en cours.
