### ISSUE TITLE
Les véhicules armés ne bougent pas avec Lucy

### ISSUE THREAD

**Issue by Mysteryjuju** [GdC-Framework/GdC_lib#15]
Quand on fait spawn un véhicule armé, il ne se déplace pas toujours.
Solution -> faire spawn le conducteur dans un groupe à part.
Impact -> rajout d'une variable en sortie pour récupérer le reste du groupe dans le véhicule (en 3ème position). On conserve le groupe conducteur en première position pour éviter de casser les scripts déjà en place : [groupe conducteur, véhicules spawn, reste du groupe].

Parce que FUCK BI.

**Comment by TheShinriel** [comment]
Tant que le premier group renvoyer est celui du conducteur, cela ne devrait pas trop déranger ceux qui utilisaient le spawn véhicule

**Comment by Sparfell** [comment]
Donc apparemment le problème a été corrigé de la façon suivante :
`_group selectLeader (effectiveCommander _veh);`
