### ISSUE TITLE
Arguments pour l'aéronef (gdc_halo)

### ISSUE THREAD

**Issue by Sweedn** [GdC-Framework/GdC_lib#30]
Serait-il possible d'obtenir un argument supplémentaire à passer dans la fonction gdc_halo afin d'ajouter du code à l'aéronef utilisé ?
Typiquement : appeler du code supplémentaire, changer le camo du véhicule...

Dans mon cas précis, il s'agit également d'utiliser la bonne source d'animation pour ouvrir la porte arrière pour le largage des hommes sur un Y-32 Xi'an, en l'état "Door_1_source".

**Comment by Sparfell** [comment]
C'est une porte latérale c'est ça ?

**Comment by Sweedn** [comment]
Soute arrière.

**Comment by Sparfell** [comment]
A part ça, ce serait possible de passer du code mais je doute de l'intérêt. T'as d'autres idées en tête à part le changement de texture ? Parce que la texture d'un véhicule que tu ne vois de l'extérieur que très brièvement et d'assez loin ça me parait pas très important.

**Comment by Sweedn** [comment]
J'ai quelques idées. Le changement de textures n'est qu'un exemple parmi d'autres.

**Comment by Sparfell** [comment]
Ben donne-les si tu veux me motiver à implémenter l'option. :D

**Comment by Sweedn** [comment]
J'aimerais avoir aussi la possibilité de choisir le side de l'aéronef, ceci me serait fort utile.

**Comment by Sparfell** [comment]
Désormais, dans la version actuelle, l'avion a le side de sa classe. Donc par exemple si c'est un C-130 US il est blufor et si c'est un Y-32 Xi'an il est opfor.
Il faut que je modifie ça donc je peux ajouter l'option au passage.

**Comment by Sparfell** [comment]
@Sweedn : 
https://github.com/GdC-Framework/GdC_lib/pull/36/commits/81ea1af482e7314e6d53ce96ec1368212744e94c

**Comment by Sweedn** [comment]
On peut clore ce ticket.
