### ISSUE TITLE
LUCY : créer une meilleure version de spawnGroupVehicle

### ISSUE THREAD

**Issue by Mysteryjuju** [GdC-Framework/GdC_lib#47]
Créer des fonctions plus simples et plus nombreuses pour gérer les véhicules : 
- véhicules un par un
- différentes fonctions par type de véhicule : terrestre, maritime, aérien...
- simplifier la gestion des équipages avec une seule liste d'unités et utiliser moveInAny

**Comment by Sparfell** [comment]
A-t-on réellement besoin de différentes fonctions suivant le type du véhicule ?

**Comment by Mysteryjuju** [comment]
Idéalement, non. Celle que tu as fait devrait tout supporter non ?

**Comment by Sparfell** [comment]
Oui en principe.
