### ISSUE TITLE
PLUTO doesn't work on local multiplayer mode (GDC_lib 1.9.4)

### ISSUE THREAD

**Issue by Tanin69** [GdC-Framework/GdC_lib#54]
Pluto works on SP Mode, but not on local multiplayer mode.

**Comment by Mysteryjuju** [comment]
Je dirais que cette ligne devrait être incriminée : 
[https://github.com/GdC-Framework/GdC_lib/blob/master/gdc_lib_main/functions/gdc_pluto/fn_pluto.sqf#L43](url)
