### ISSUE TITLE
Multiples waypoints pour les groupes gérés par GDC_fnc_lucyGroupRandomPatrol

### ISSUE THREAD

**Issue by Tanin69** [GdC-Framework/GdC_lib#76]
Si le script est exécuté sur le serveur (dédié) ou le HC, certains groupes ont des WP multiples lorsqu'ils sont appelés avec la fonction GDC_fnc_lucyGroupRandomPatrol.

Comment reproduire : spawner une dizaine de groupes, les passer à la fonction GDC_fnc_lucyGroupRandomPatrol. Généralement, un groupe a déjà de multiples WP.

Avec le temps de mission passant, le nombre de groupes avec des WP multiples et le nombre de WP par groupe augmente.

**Comment by Tanin69** [comment]
Lié à un fonctionnement étrange de setWaypointStatements :
"The Condition code is evaluated on the group owner's machine. When condition returns true, for some strange reason, the condition is evaluated one more time. The OnActivation code is executed globally, a.k.a on every client! See Waypoints."

**Comment by Sparfell** [comment]
> 
> 
> Une solution possible à testée. Remplacer par un `if(local this) then {<code>};` devrait permettre d'exécuter le code uniquement sur la machine local au groupe.

Si cette sécurité n'est pas susceptible de causer d'autres soucis, ça vaut le coup d'essayer.
