### ISSUE TITLE
Add white list for fn_chooseSpawnPos.sqf

### ISSUE THREAD

**Issue by Tanin69** [GdC-Framework/GdC_lib#83]
Add a white list for markers, black list already implented.

**Comment by TheShinriel** [comment]
Vu qu'on propose un point précis, et qu'on vérifie s'il est présent dans la Black list, afin de l'ignorer.

Est-ce que ça a du sens d'avoir à la fois une whitelist et blacklist ?
Un boolean, afin de déterminer le comportement, blacklist ou whitelist n'aurait-il pas plus de sens?

**Comment by Tanin69** [comment]
Boolean ou pas, la question est de pouvoir limiter le spawn à une ou deux zones sans avoir à se taper l'exclusion de toutes les autres zones de la carte. S'il y a moyen de faire sans modifier le code, je suis preneur.

**Comment by TheShinriel** [comment]
Ajouter un paramètre n'a aucun intérêt, ce que tu cherches c'est de
demander plusieurs marqueur au lieu d'un en premier paramètre...
Tu peux en réalité déjà le faire

https://github.com/GdC-Framework/GdC_lib/blob/d94afa14216bd74ad186d658cdafcbd284f229cf/gdc_lib_main/functions/util/fn_chooseSpawnPos.sqf
1) Tu met un marqueur englobant toutes la zone que tu veux
2) blacklistant tout sauf le peu que tu veux

La solution que je propose, de proposer en premier paramètre un marqueur ou
une liste de marqueur, ferait le taff...
Puisque c'est justement CA déjà ta whitelist... c'est le marqueur où tu
peux choisir le spawn.

**Comment by Tanin69** [comment]
@TheShinriel essaie donc sur une map, par exemple en regardant la mission 122mm.

**Comment by TheShinriel** [comment]
Je vois bien le code qui fait du blacklist

//Spawn au choix des joueurs
_tbMrkNoSpawn =
["mrkNoSpawn_1","mrkNoSpawn_2","mrkNoSpawn_3","mrkNoSpawn_4","mrkNoSpawn_5","mrkNoSpawn_5","mrkNoSpawn_6","mrkNoSpawn_7","mrkNoSpawn_8","mrkNoSpawn_9","mrkNoSpawn_10"];
["mk_spawn",[boat_1,boat_2,boat_3,boat_4,boat_5],"MAJOR",_tbMrkNoSpawn,2]
call GDC_fnc_chooseSpawnPos;

Mais je ne vois pas en quoi passer le premier paramètre comme un marqueur
ou une liste marqueur, n'est pas une solution ?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by TheShinriel** [comment]
Après relecture, j'avais mal compris le premier paramètre, qui est le marker qui se déplace

Après je continue de ne pas aimer un switch Black/white list
Je préfère avoir les 2.

Permettant de faire un Carré, et blacklistant le centre :) afin de permettre de spawn tout autour d'un objectif
