### ISSUE TITLE
fn_extraCall, obligé d'avoir la radio demandé comme active

### ISSUE THREAD

**Issue by TheShinriel** [GdC-Framework/GdC_lib#9]
La condition ligne 17 de fn_extraCall.sqf

`if ((([] call acre_api_fnc_getCurrentRadioChannelNumber) == gdc_extra_chan) AND (([([] call acre_api_fnc_getCurrentRadio)] call acre_api_fnc_getBaseRadio) == gdc_extra_radio)) then {`

Pourrait être changé, pour permettre de vérifier que le joueur A la radio et sur le bon canal, plutôt que de l'avoir forcément active. Pour des gars comme qui préfère utiliser les raccourcis claviers plutôt que le cycle des radios.

**Comment by TheShinriel** [comment]
Method that can be used **acre_api_fnc_hasRadio**
Documentation here => http://acre.idi-systems.com/api/api_general.html#acre_api_fnc_hasRadio

**Comment by Sparfell** [comment]
Plutôt **acre_api_fnc_hasKindOfRadio**  qui est déjà utilisée en amont dans https://github.com/GdC-Framework/GdC_lib/blob/master/gdc_lib_main/functions/gdc_extra/fn_extra.sqf
On pourrait tout simplement virer la condition de radio sélectionnée car de toute façon l'action n'apparaît pas si le joueur n'a pas la bonne radio (voir lien ci-dessus).

**Comment by Sparfell** [comment]
Mais du coup si le joueur a une autre radio réglée sur le "bon" canal alors que la "bonne" radio est réglée sur un mauvais canal, il peut tout de même utiliser l'action. Est-ce très grave ? Pas sûr.

**Comment by TheShinriel** [comment]
J'comptais récupérer la liste de radio et voir les infos qu'on avait, si on avait le canal (je suppose sinon j'vois pas comment ils font ^^)

Mais comme j'ai pas vu de radio pour récupérer le canal d'un radio en particulier ^^ (et non l'active)

Mais oui le kindOf serait une bonne manière de vérifier qu'il a au moins une bonne radio

**Comment by Sparfell** [comment]
En fait on peut peut-être tout simplement juste vérifier que le joueur a la bonne radio. A l'époque il y avait la vérification du canal et de la radio activée pour que l'action du menu molette ne soit pas disponible en permanence pour des questions d'encombrement du dit menu. Maintenant que l'action est dans le menu ACE ce n'est plus très utile.
Le problème c'est qu'on ne peut pas changer les paramètres de la fonction à ce stade donc à moins de trouver un remplaçant au second paramètre...

**Comment by TheShinriel** [comment]
Je regarde ce soir si on peut garder cette contrainte.

Mais concernant la signature de la méthode, passer un paramètre obsolète, c'est moche, mais bon tu restes retro compatible ;)

**Comment by TheShinriel** [comment]
J'ai directement vérifié l'api d'acre
=> https://github.com/IDI-Systems/acre2/tree/master/addons/api

La méthode pour récupérer le canal d'une radio existe ( https://github.com/IDI-Systems/acre2/blob/master/addons/api/fnc_getRadioChannel.sqf ) je ne l'avais pas vu dans la doc


On pourrait utiliser la méthode

`["ACRE_PRC117f"] call acre_api_fnc_getRadioByType`
( https://github.com/IDI-Systems/acre2/blob/master/addons/api/fnc_getRadioByType.sqf )
`["acre_prc117f_id_1"] call acre_api_fnc_getRadioChannel;`
( https://github.com/IDI-Systems/acre2/blob/master/addons/api/fnc_getRadioChannel.sqf )

Sauf que la première méthode ne renvoi que la PREMIÈRE radio trouvée du type demandé, c'est à dire potentiellement pas la bonne, s'il en a plusieurs.

```
_rightRadio = false;
{
if(["acre_prc117f_id_1"] call acre_api_fnc_getRadioChannel) then {
_rightRadio = true;
};
} foreach ([] call acre_api_fnc_getCurrentRadioList);
```

**Comment by TheShinriel** [comment]
Une proposition de pull request pour gérer le cas => https://github.com/GdC-Framework/GdC_lib/pull/10

J'ai du en faire un peu plus... parce qu'il manque les fuckings methodes de bases pour comparer des strings -_-
D'où l'ajout de fonction interne pour la lib
